dbfilename redis_cache.rdb
dir /home/vineelreddykamireddy/frappe/scanifyme/config/pids
pidfile /home/vineelreddykamireddy/frappe/scanifyme/config/pids/redis_cache.pid
bind 127.0.0.1
port 13002
maxmemory 324mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/vineelreddykamireddy/frappe/scanifyme/config/redis_cache.acl
