dbfilename redis_queue.rdb
dir /home/vineelreddykamireddy/frappe/scanifyme/config/pids
pidfile /home/vineelreddykamireddy/frappe/scanifyme/config/pids/redis_queue.pid
bind 127.0.0.1
port 11002

aclfile /home/vineelreddykamireddy/frappe/scanifyme/config/redis_queue.acl
